'use strict';
const CACHE_NAME='miranch-v-microoperacion-metricas-20260908-01';
const SHELL=[
 './index.html','./manifest.json','./icon-192.png','./icon-512.png','./apple-touch-icon.png','./icon-miranch.png',
 './iranch-modular/assets/header-sunrise.webp','./iranch-modular/assets/home-semana-4.webp','./iranch-modular/assets/logo-miranch-horizontal.png','./iranch-modular/assets/logo-miranch-vertical.png',
 './iranch-modular/modules/firebase-bootstrap.js','./iranch-modular/modules/core/telemetry.js','./iranch-modular/modules/view-loader.js','./iranch-modular/modules/module-loader.js','./iranch-modular/modules/core/module-contracts.js','./iranch-modular/modules/core/runtime.js','./iranch-modular/modules/core/firebase-contract.js','./iranch-modular/modules/core/i18n-data.js','./iranch-modular/modules/core/state.js','./iranch-modular/modules/core/date-utils.js','./iranch-modular/modules/core/dom-utils.js','./iranch-modular/modules/core/ui-feedback.js','./iranch-modular/modules/app-core.js','./iranch-modular/modules/core/i18n-export.js','./iranch-modular/modules/core/local-demo-errors.js','./iranch-modular/modules/core/account-auth.js'
];
self.addEventListener('install',e=>e.waitUntil(caches.open(CACHE_NAME).then(c=>c.addAll(SHELL)).then(()=>self.skipWaiting())));
self.addEventListener('activate',e=>e.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k!==CACHE_NAME).map(k=>caches.delete(k)))).then(()=>self.clients.claim())));
self.addEventListener('fetch',e=>{const r=e.request;if(r.method!=='GET')return;const u=new URL(r.url);if(u.origin!==self.location.origin)return;if(r.mode==='navigate'){e.respondWith(fetch(r).then(res=>{const c=res.clone();caches.open(CACHE_NAME).then(x=>x.put('./index.html',c));return res}).catch(()=>caches.match('./index.html')));return}e.respondWith(caches.match(r).then(c=>c||fetch(r).then(res=>{if(res&&res.ok){const cp=res.clone();caches.open(CACHE_NAME).then(x=>x.put(r,cp))}return res})))});
self.addEventListener('push',e=>{let d={};try{d=e.data?e.data.json():{}}catch(_){d={body:e.data?e.data.text():''}}e.waitUntil(self.registration.showNotification(d.title||'MiRanch',{body:d.body||'Tienes una nueva notificación',icon:'./icon-192.png',badge:'./icon-192.png',data:{url:d.url||'./index.html'}}))});
self.addEventListener('notificationclick',e=>{e.notification.close();const t=e.notification?.data?.url||'./index.html';e.waitUntil(self.clients.matchAll({type:'window',includeUncontrolled:true}).then(cs=>{for(const c of cs)if('navigate'in c&&'focus'in c)return c.navigate(t).then(()=>c.focus());return self.clients.openWindow(t)}))});
self.addEventListener('message',e=>{if(!e.data||e.data.type!=='IRANCH_LOCAL_NOTIFICATION')return;e.waitUntil(self.registration.showNotification(e.data.title||'MiRanch',{body:e.data.body||'',icon:'./icon-192.png',badge:'./icon-192.png',data:{url:e.data.url||'./index.html'}}))});
